#!/usr/bin/env node
"use strict";

/**
 *
 * This is a mock of the `npm` CLI, for testing purposes.
 * It just records the CLI arguments in a JSON file.
 *
 */

const mocks = require("../../utils/mocks");
mocks.record("npm", process.argv.slice(2));
